# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_wiki_neg_answers_t5:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /home/ec2-user/src/data/psgs_w100_neg_answers.tsv
  id_prefix: 'wiki:'