# @package _group_

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train

nq_train_hn1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-adv-hn-train

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/nq-dev.json

nq_dev_sample:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/nq-dev-sample.json

new_nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/new-nq-dev.json

new_nq_dev_negative:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/new-nq-dev-negative.json

new_nq_dev_hard_negative:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/new-nq-dev-hard-negative.json

new_nq_dev_pos_injected:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/new-nq-dev-injected-positives.json

new_nq_t5_negative:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/t5_modified_pos_ctx_nq_dev.json

new_nq_unk:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/new-nq-dev-unk.json

new_nq_shift_1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /home/yilu/DPR/dpr/downloads/data/retriever/new-nq-dev-shift-1.json

trivia_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train

trivia_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-dev

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

webq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-train

webq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-dev

curatedtrec_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-train

curatedtrec_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-dev
